name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1
      - name: Install Depot
        uses: cognitive-engineering-lab/depot/actions/install@main
      - name: Build
        run: depot build --release
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - uses: actions/deploy-pages@v4        